<?php
/* Generated by CRUDigniter v2.3 Beta 
* www.crudigniter.com
*/
 
class Perangkat extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        if($this->session->userdata('isLogin') != TRUE)
            redirect('dashboard');
        $this->load->model('Perangkat_model');
    } 

    /*
     * Listing of perangkat
     */
    function index()
    {
        $data["menu"] = "Perangkat";
        $data['perangkat'] = $this->Perangkat_model->get_all_perangkat();
        $data["title"] = 'Perangkat';
        $this->load->view('perangkat/index',$data);
    }

    /*
     * Adding a new perangkat
     */
    function add()
    {   
        $this->load->library('form_validation');

        $this->form_validation->set_rules('nama_perangkat','Nama Perangkat','required');
        $this->form_validation->set_rules('ip_address','Ip Address','required');
        $this->form_validation->set_rules('latitude','Latitude','required');
        $this->form_validation->set_rules('longitude','Longitude','required');
        
        if($this->form_validation->run())     
        {   
            $params = array(
                'id_kota' => $this->input->post('id_kota'),
                'nama_perangkat' => $this->input->post('nama_perangkat'),
                'ip_address' => $this->input->post('ip_address'),
                'keterangan' => $this->input->post('keterangan'),
                'latitude' => $this->input->post('latitude'),
                'longitude' => $this->input->post('longitude'),
            );
            
            $perangkat_id = $this->Perangkat_model->add_perangkat($params);
            redirect('perangkat/index');
        }
        else
        {
            $data["menu"] = "Perangkat";
            $this->load->model('Kota_model');
            $data['all_kota'] = $this->Kota_model->get_all_kota();
            $data["title"] = 'Perangkat';
                
            $this->load->view('perangkat/add',$data);
        }
    }  

    /*
     * Editing a perangkat
     */
    function edit($id_perangkat)
    {   
        // check if the perangkat exists before trying to edit it
        $perangkat = $this->Perangkat_model->get_perangkat($id_perangkat);
        $data["menu"] = "Perangkat";
        
        if(isset($perangkat['id_perangkat']))
        {
            $this->load->library('form_validation');

            $this->form_validation->set_rules('nama_perangkat','Nama Perangkat','required');
            $this->form_validation->set_rules('ip_address','Ip Address','required');
            $this->form_validation->set_rules('latitude','Latitude','required');
            $this->form_validation->set_rules('longitude','Longitude','required');
        
            if($this->form_validation->run())     
            {   
                $params = array(
                    'id_kota' => $this->input->post('id_kota'),
                    'nama_perangkat' => $this->input->post('nama_perangkat'),
                    'ip_address' => $this->input->post('ip_address'),
                    'keterangan' => $this->input->post('keterangan'),
                    'latitude' => $this->input->post('latitude'),
                    'longitude' => $this->input->post('longitude'),
                );

                $this->Perangkat_model->update_perangkat($id_perangkat,$params);            
                redirect('perangkat/index');
            }
            else
            {   
                $data['perangkat'] = $this->Perangkat_model->get_perangkat($id_perangkat);
    
                $this->load->model('Kota_model');
                $data['all_kota'] = $this->Kota_model->get_all_kota();
                $data['title'] = 'Perangkat';
                $this->load->view('perangkat/edit',$data);
            }
        }
        else
            show_error('The perangkat you are trying to edit does not exist.');
    } 

    /*
     * Deleting perangkat
     */
    function remove($id_perangkat)
    {
        $perangkat = $this->Perangkat_model->get_perangkat($id_perangkat);

        // check if the perangkat exists before trying to delete it
        if(isset($perangkat['id_perangkat']))
        {
            $this->Perangkat_model->delete_perangkat($id_perangkat);
            redirect('perangkat/index');
        }
        else
            show_error('The perangkat you are trying to delete does not exist.');
    }
    
}