<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Kota_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get kotum by id_kota
     */
    function get_kotum($id_kota)
    {
        return $this->db->get_where('kota',array('id_kota'=>$id_kota))->row_array();
    }
    
    /*
     * Get all kota
     */
    function get_all_kota()
    {
        return $this->db->get('kota')->result_array();
    }
    
    /*
     * function to add new kotum
     */
    function add_kotum($params)
    {
        $this->db->insert('kota',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update kotum
     */
    function update_kotum($id_kota,$params)
    {
        $this->db->where('id_kota',$id_kota);
        $this->db->update('kota',$params);
    }
    
    /*
     * function to delete kotum
     */
    function delete_kotum($id_kota)
    {
        $this->db->delete('kota',array('id_kota'=>$id_kota));
    }
}
