<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Perangkat_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get perangkat by id_perangkat
     */
    function get_perangkat($id_perangkat)
    {
        return $this->db->get_where('perangkat',array('id_perangkat'=>$id_perangkat))->row_array();
    }
    
    /*
     * Get all perangkat
     */
    function get_all_perangkat()
    {
        $this->db->select('perangkat.*');
        $this->db->select('kota.nama_kota');
        $this->db->join('kota',"kota.id_kota=perangkat.id_kota");
        return $this->db->get('perangkat')->result_array();
    }
    
    /*
     * function to add new perangkat
     */
    function add_perangkat($params)
    {
        $this->db->insert('perangkat',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update perangkat
     */
    function update_perangkat($id_perangkat,$params)
    {
        $this->db->where('id_perangkat',$id_perangkat);
        $this->db->update('perangkat',$params);
    }
    
    /*
     * function to delete perangkat
     */
    function delete_perangkat($id_perangkat)
    {
        $this->db->delete('perangkat',array('id_perangkat'=>$id_perangkat));
    }
}